"use client";
import Image from "next/image";
import {
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
  getKeyValue,
} from "@nextui-org/react";
import React from "react";
export default function Home() {
  const rows = [
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "1",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "2",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "3",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Puertas del sol",
      numerodemanzana: "4",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "1",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "2",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "3",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Tierra y Libertad",
      numerodemanzana: "4",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "1",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "2",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "3",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },

    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "1",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "2",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "3",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "4",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "5",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "6",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "7",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "8",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "9",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "10",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "11",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "12",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "13",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "14",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "15",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "16",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "17",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "18",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "19",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "20",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "21",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "22",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "23",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "24",
      costodelterreno: "350,000 MXN",
    },
    {
      key: "1",
      nombredelfraccionamiento: "Las Flores",
      numerodemanzana: "4",
      numerodellote: "25",
      costodelterreno: "350,000 MXN",
    },
  ];

  const columns = [
    {
      key: "nombredelfraccionamiento",
      label: "Nombre del Fraccionamiento",
    },

    {
      key: "numerodemanzana",
      label: "Numero de la manzana",
    },
    {
      key: "numerodellote",
      label: "Numero del lote",
    },
    {
      key: "costodelterreno",
      label: "Costo total del terreno",
    },
  ];

  return (
    <main className="  p-5">
      <Table aria-label="" className="">
        <TableHeader
          className="font-thin justify-items-center"
          columns={columns}
        >
          {(column) => (
            <TableColumn
              className="text-red-800 font-bold text-base"
              key={column.key}
            >
              {column.label}
            </TableColumn>
          )}
        </TableHeader>
        <TableBody items={rows}>
          {(item) => (
            <TableRow className=" " key={item.key}>
              {(columnKey) => (
                <TableCell className=" shadow-slate-200 border text-black">
                  {getKeyValue(item, columnKey)}
                </TableCell>
              )}
            </TableRow>
          )}
        </TableBody>
      </Table>
    </main>
  );
}
